export const LOGIN_USER = "LOGIN_USER";
export const LOADING_USER = "LOADING_USER";
export const SET_USER_ERROR = "SET_USER_ERROR";
export const SET_UNAUTHENTICATED = "SET_UNAUTHENTICATED";
export const LOADING_UI = "LOADING_UI";
export const STOP_LOADING_UI = "STOP_LOADING_UI";
export const SET_UI_ERROR = "SET_UI_ERROR";

export const LOADING_ROOM = "LOADING_ROOM";
export const SET_ROOM = "SET_ROOM";
export const ERROR_ROOM = "ERROR_ROOM";
export const STOP_LOADING_ROOM = "STOP_LOADING_ROOM";
export const CREATE_ROOM = "CREATE_ROOM";
export const UPDATE_ROOM = "UPDATE_ROOM";
export const RESERVE_ROOM = "RESERVE_ROOM";
export const RESERVE_AND_OCCUPY_ROOM = "RESERVE_AND_OCCUPY_ROOM";
export const UNRESERVE_ROOM = "UNRESERVE_ROOM";
export const REMOVE_RESERVATION = "REMOVE_RESERVATION";
export const EDIT_CHECKIN_ROOM = "EDIT_CHECKIN_ROOM";

export const LOADING_OPERATOR = "LOADING_OPERATOR";
export const SET_OPERATOR = "SET_OPERATOR";
export const ERROR_OPERATOR = "ERROR_OPERATOR";
export const STOP_LOADING_OPERATOR = "STOP_LOADING_OPERATOR";
export const CREATE_OPERATOR = "CREATE_OPERATOR";
export const UPDATE_OPERATOR = "UPDATE_OPERATOR";
export const DELETE_OPERATOR = "DELETE_OPERATOR";

export const LOADING_STORE = "LOADING_STORE";
export const SET_STORE = "SET_STORE";
export const ERROR_STORE = "ERROR_STORE";
export const STOP_LOADING_STORE = "STOP_LOADING_STORE";
export const CREATE_STORE = "CREATE_STORE";
export const UPDATE_STORE = "UPDATE_STORE";

export const LOADING_LEDGER = "LOADING_LEDGER";
export const SET_LEDGER = "SET_LEDGER";
export const ERROR_LEDGER = "ERROR_LEDGER";
export const STOP_LOADING_LEDGER = "STOP_LOADING_LEDGER";
export const CREATE_LEDGER = "CREATE_LEDGER";
export const UPDATE_LEDGER = "UPDATE_LEDGER";

export const LOADING_CUSTOMER = "LOADING_CUSTOMER";
export const SET_CUSTOMER = "SET_CUSTOMER";
export const SET_MORE_CUSTOMER = "SET_MORE_CUSTOMER";
export const ERROR_CUSTOMER = "ERROR_CUSTOMER";
export const STOP_LOADING_CUSTOMER = "STOP_LOADING_CUSTOMER";
export const CREATE_CUSTOMER = "CREATE_CUSTOMER";
export const UPDATE_CUSTOMER = "UPDATE_CUSTOMER";
export const CHECKOUT_CUSTOMER = "CHECKOUT_CUSTOMER";
export const EXTRA_CHARGE_CUSTOMER = "EXTRA_CHARGE_CUSTOMER";
export const EDIT_LOADING = "EDIT_LOADING";
export const STOP_EDIT_LOADING = "STOP_EDIT_LOADING";
export const EDIT_CHECKIN_CUSTOMER = "EDIT_CHECKIN_CUSTOMER";
export const EDIT_CHECKIN_CUSTOMER_EXTRA_CHARGES =
  "EDIT_CHECKIN_CUSTOMER_EXTRA_CHARGES";
export const HAS_MORE_CUSTOMERS = "HAS_MORE_CUSTOMERS";
export const NO_MORE_CUSTOMERS = "NO_MORE_CUSTOMERS";
export const LOADING_MORE_CUSTOMERS = "LOADING_MORE_CUSTOMERS";
export const STOP_LOADING_MORE_CUSTOMERS = "STOP_LOADING_MORE_CUSTOMERS";

export const EDIT_RESERVATION_ROOM = "EDIT_RESERVATION_ROOM";
export const EDIT_RESERVATION_CUSTOMER = "EDIT_RESERVATION_CUSTOMER";
export const EDIT_CUSTOMER_RESERVATION = "EDIT_CUSTOMER_RESERVATION";
export const EDIT_CUSTOMER_RESERVATION_ROOM = "EDIT_CUSTOMER_RESERVATION_ROOM";
export const DELETE_RESERVATION = "DELETE_RESERVATION";

export const LOADING_TRANSACTION = "LOADING_TRANSACTION";
export const SET_TRANSACTION = "SET_TRANSACTION";
export const SET_MORE_TRANSACTION = "SET_MORE_TRANSACTION";
export const ERROR_TRANSACTION = "ERROR_TRANSACTION";
export const STOP_LOADING_TRANSACTION = "STOP_LOADING_TRANSACTION";
export const CREATE_TRANSACTION = "CREATE_TRANSACTION";
export const UPDATE_TRANSACTION = "UPDATE_TRANSACTION";
export const TRANSACTION_EDIT_LOADING = "TRANSACTION_EDIT_LOADING";
export const STOP_TRANSACTION_EDIT_LOADING = "STOP_TRANSACTION_EDIT_LOADING";
export const EDIT_TRANSACTION_GUEST = "EDIT_TRANSACTION_GUEST";
export const EDIT_TRANSACTION = "EDIT_TRANSACTION";
export const SYNC_TRANSACTION = "SYNC_TRANSACTION";
export const HAS_MORE_TRANSACTIONS = "HAS_MORE_TRANSACTIONS";
export const NO_MORE_TRANSACTIONS = "NO_MORE_TRANSACTIONS";
export const LOADING_MORE_TRANSACTIONS = "LOADING_MORE_TRANSACTIONS";
export const STOP_LOADING_MORE_TRANSACTIONS = "STOP_LOADING_MORE_TRANSACTIONS";

export const LOADING_COMPANY = "LOADING_COMPANY";
export const SET_COMPANY = "SET_COMPANY";
export const SET_COMPANY_LOGO = "SET_COMPANY_LOGO";
export const ERROR_COMPANY = "ERROR_COMPANY";
export const STOP_LOADING_COMPANY = "STOP_LOADING_COMPANY";
export const CREATE_COMPANY = "CREATE_COMPANY";
export const UPDATE_COMPANY = "UPDATE_COMPANY";
export const EDIT_COMPANY_LOADING = "EDIT_COMPANY_LOADING";
export const STOP_EDIT_COMPANY_LOADING = "STOP_EDIT_COMPANY_LOADING";
export const CLEAR_DATA = "CLEAR_DATA";
export const CREATE_INVOICE = "CREATE_INVOICE";
