const dummyData = {
  country: "INDIA",
  state: "UTTARAKHAND",
  jurisdiction: "dsfvsf",
  companyMobile: 3245234543,
  manufacturingLicenseNumber: "245252",
  dlNumber: "3r433",
  foodLicenseNumber: "4242424",
  vatNumber: "42424",
  operatorName: "sardul",
  invoice_no: "ECOR-00010",
  balance: 329.28,
  companyName: "E CORP",
  companyAddress: "asdas,asdas,asdas,dasdasadf,fdfasd,, , asdasasd",
  trans_date: "2021-02-09",
  subTotal: 340.23,
  gstNumber: "fdsfrw333",
  gstAmount: 35.28,
  discount: 46.32,
  extraDiscount: 0,
  items: [
    {
      sno: 1,
      desc: "Butter Chicken",
      discount: 13,
      discountType: "%",
      gst: 12,
      rate: 160,
      qty: 1,
      variant: "half",
    },
    {
      sno: 2,
      desc: "Mushroom ",
      discount: 14,
      discountType: "%",
      gst: 12,
      rate: 180,
      qty: 1,
      variant: "half",
    },
  ],
};
export default dummyData;
